#!/usr/bin/env python3
"""Rebuild MANIFEST.json for a release. Committed with v1.0.1 so the root hash is reproducible by anyone.

Formula (v1.0.1 onward):
  file hash  = sha256 of the file bytes, for every *.json and *.md under data/
  root_hash  = sha256 of the UTF-8 text made of the lines "<sha256>  <path>\\n", one per file, sorted by path
               (exactly the output of the manifest's own verification_command, hashed)
Note: the v1.0.0 root hash was produced by a script that was never committed and its formula could not be
reproduced, so v1.0.0's published root hash stands as a historical value and cannot be regenerated by this tool.

Usage: python3 build_manifest.py <version> [--write]
"""
import datetime
import hashlib
import json
import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
VERIFY = (r"find data -type f \( -name '*.json' -o -name '*.md' \) -exec sha256sum {} \; | sort -k2 > local_manifest.txt"
          r""" && diff <(jq -r '.files[] | "\(.sha256)  \(.path)"' MANIFEST.json | sort -k2) local_manifest.txt"""
          r" && echo root_hash: $(sort -k2 local_manifest.txt | sha256sum | cut -d' ' -f1)")


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    version = sys.argv[1]
    write = "--write" in sys.argv
    os.chdir(ROOT)
    entries = []
    for dp, _, fns in os.walk("data"):
        for fn in fns:
            if fn.endswith((".json", ".md")):
                p = os.path.join(dp, fn).replace(os.sep, "/")
                entries.append({"path": p, "sha256": sha256_file(p)})
    entries.sort(key=lambda e: e["path"])
    text = "".join(f"{e['sha256']}  {e['path']}\n" for e in entries)
    root = hashlib.sha256(text.encode("utf-8")).hexdigest()
    with open("MANIFEST.json") as fh:
        old = json.load(fh)
    keep = ("manifest_version", "dataset_name", "maintainer", "license", "license_url", "hash_algorithm")
    m = {k: old[k] for k in keep if k in old}
    m["dataset_version"] = version
    m["generated"] = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    m["description"] = old["description"].replace("v1.0.0", f"v{version}")
    m["verification_command"] = VERIFY
    m["root_hash_formula"] = ("sha256 of the text made of the lines '<sha256>  <path>' (newline-terminated, sorted by path) "
                              "for every *.json and *.md under data/; see data/tools/qa/build_manifest.py")
    m["files"] = entries
    m["file_count"] = len(entries)
    m["root_hash"] = root
    print(f"v{version}: {len(entries)} files, root_hash {root}")
    if write:
        with open("MANIFEST.json", "w") as fh:
            json.dump(m, fh, indent=2, ensure_ascii=False)
            fh.write("\n")
        print("MANIFEST.json written")


if __name__ == "__main__":
    main()
